[package]
name = "groundctrl-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1"
tokio-serial = "5"
num-traits = { workspace = true }
mavlink = { workspace = true }
