[package]
name = "groundctrl-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
groundctrl-core = { path = "../core" }
tokio = { workspace = true }
mavlink = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
